# Generated by Django 3.0.3 on 2020-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
