# Generated by Django 3.0.3 on 2020-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
